Repository PM4-FS25-DropIn/dropin, pull requests merged in 2025-06, with the labels that each got.

#217 Feature/readme
  README.md
  docs/CONTRIBUTION.md
  docs/DEPLOYMENT.md
  docs/DefinitionOfDone.md
  docs/FeatureSpecifications.md
  docs/GETTING_STARTED.md
  docs/INFRASTRUCTURE.md
  docs/README.md
  docs/Team.md
  docs/client/VISUAL_CONCEPT.md
  docs/client/VisualConcept.md
  docs/defintion_of_DONE.md
  docs/images/ER-Diagram.png
  docs/images/dropin-mockup-assets/ChatView Chat - Light.png
  docs/images/dropin-mockup-assets/ChatView List - Light.png
  docs/images/dropin-mockup-assets/CreateView - Light.png
  docs/images/dropin-mockup-assets/For You - Light.png
  docs/images/dropin-mockup-assets/Map (Event Details, short) - Light.png
  docs/images/dropin-mockup-assets/SignIn.png
  docs/images/icon.webp
  docs/server/ARCHITECTURE.md
  docs/server/Architecture.md
  docs/server/SupabaseDeploymentAndConfiguration.md
Labels: documentation

#201 Bug/add back removed migrations
  client/supabase/migrations/20250411161728_create_avatar_bucket_rls.sql
  client/supabase/migrations/20250421203700_limit_avatar_file_type_size_amount.sql
  client/supabase/migrations/20250426203800_change_emojicode_constraint.sql
  client/supabase/migrations/20250429224800_apply_new_fields_on_new_user.sql
  server/test/database/avatar.test.ts
  server/test/database/dbhelpers.ts
  server/test/database/event.test.ts
  server/test/database/event_joins.test.ts
Labels: bug

#219 Fixed urls and some minor improvements
  README.md
  client/ios/DropIn/CoreViews/AboutView.swift
  client/ios/DropIn/CoreViews/ProfileView.swift
  client/ios/DropIn/Info.plist
  client/ios/DropIn/Services/AuthService.swift
Labels: enhancement
