Repository PM4-FS25-DropIn/dropin, pull requests merged in 2025-04, with the labels that each got.

#65 Create defintion_of_DONE.md
  docs/defintion_of_DONE.md
Labels: documentation

#37 35 [VIEW] App Core View Navigation
  client/ios/dropin.xcodeproj/project.pbxproj
  client/ios/dropin/AppView.swift
  client/ios/dropin/Components/TabBar.swift
  client/ios/dropin/ContentView.swift
Labels: enhancement

#36 26 [VIEW] - Implement First HomeView
  client/ios/dropin/Assets.xcassets/default.event.thumbnail.imageset/Contents.json
  client/ios/dropin/Assets.xcassets/default.event.thumbnail.imageset/Screenshot 2025-03-31 at 17.22.05.png
  client/ios/dropin/Components/EventCard.swift
  client/ios/dropin/Components/EventCategoryTabView.swift
  client/ios/dropin/Components/EventQuickInfo.swift
  client/ios/dropin/Components/EventStatusBadge.swift
  client/ios/dropin/Components/FriendAvatar.swift
  client/ios/dropin/Components/FriendAvatarCarousel.swift
  client/ios/dropin/CoreViews/EventDetailView.swift
  client/ios/dropin/CoreViews/HomeView.swift
  client/ios/dropin/DummyEvent.swift
  client/ios/dropin/Models.swift
Labels: enhancement

#66 First Version of ChatListView vibecoded
  client/ios/dropin/Chats/ChatListView.swift
  client/ios/dropin/CoreViews/HomeView.swift
Labels: enhancement

#73 Entire profile view scrollable (+ parallax effect)
  client/ios/dropin/CoreViews/ProfileView.swift
Labels: enhancement

#79 Bio text refinement
  client/ios/dropin/CoreViews/ProfileView.swift
  client/ios/dropin/ExpandableText.swift
Labels: enhancement

#82 Fix expandable text
  client/ios/dropin.xcodeproj/project.pbxproj
  client/ios/dropin/CoreViews/ProfileView.swift
  client/ios/dropin/ExpandableText.swift
  client/ios/dropin/dropin.entitlements
Labels: bug

#81 Drop in list tab switching
  client/ios/dropin/CoreViews/DropInListView.swift
  client/ios/dropin/DummyEvent.swift
Labels: enhancement

#77 71 Create initial db schema with local supabase for frontend
  .github/workflows/cd-server.yml
  client/supabase/.gitignore
  client/supabase/config.toml
  client/supabase/migrations/20250411161616_create_profiles_table.sql
  client/supabase/migrations/20250411161646_create_profiles_rls.sql
  client/supabase/migrations/20250411161709_create_avatar_bucket.sql
  client/supabase/migrations/20250411161728_create_avatar_bucket_rls.sql
  client/supabase/migrations/20250411161743_create_event_bucket.sql
  client/supabase/migrations/20250411161801_create_event_bucket_rls.sql
  client/supabase/migrations/20250411161852_create_events_table.sql
  client/supabase/migrations/20250411161912_create_event_bans_table.sql
  client/supabase/migrations/20250411161924_create_event_bans_rls.sql
  client/supabase/migrations/20250411161936_create_events_rls.sql
  client/supabase/migrations/20250411161953_create_event_joins_table.sql
  client/supabase/migrations/20250411162003_create_event_joins_rls.sql
  client/supabase/migrations/20250411162105_create_event_declines_table.sql
  client/supabase/migrations/20250411162117_create_event_declines_rls.sql
  client/supabase/migrations/20250411162141_create_handle_user_event_ban_function_trigger.sql
  client/supabase/migrations/20250411162202_create_handle_event_update_function_trigger.sql
  client/supabase/migrations/20250411162225_create_handle_new_user_function_trigger.sql
  client/supabase/migrations/20250411181539_create_handle_event_creation_function_trigger.sql
  client/supabase/migrations/20250411183955_create_view_events_not_responded_to.sql
  client/supabase/migrations/20250411212032_create_slotsTaken_handlers.sql
  client/supabase/migrations/20250412155222_create_view_all_joined_events_of_user.sql
  client/supabase/migrations/20250412234505_create_event_feed_fetch_function.sql
  client/supabase/migrations/20250416154200_create_event_chat_messages_table.sql
  client/supabase/migrations/20250416173000_enable_event_chat_messages_rls.sql
  client/supabase/migrations/20250416181000_add_location_column_to_event.sql
  client/supabase/migrations/20250416200300_update_profile_info.sql
  client/supabase/schemas/avatar_bucket.sql
  client/supabase/schemas/avatar_bucket_rls.sql
  client/supabase/schemas/event_bans.sql
  client/supabase/schemas/event_bans_rls.sql
  client/supabase/schemas/event_bucket.sql
  client/supabase/schemas/event_bucket_rls.sql
  client/supabase/schemas/event_declines.sql
  client/supabase/schemas/event_declines_rls.sql
  client/supabase/schemas/event_joins.sql
  client/supabase/schemas/event_joins_rls.sql
  client/supabase/schemas/events.sql
  client/supabase/schemas/events_rls.sql
  client/supabase/schemas/handle_event_update.sql
  client/supabase/schemas/handle_new_user.sql
  client/supabase/schemas/handle_user_event_ban.sql
  client/supabase/schemas/profiles.sql
  client/supabase/schemas/profiles_rls.sql
  server/Dockerfile
  server/build.docker.cmd
  server/build.docker.ps1
  server/build.docker.sh
  server/docker/docker-compose.yml
  server/entrypoint.sh
  server/package-lock.json
  server/package.json
Labels: enhancement

#76 Swift - Codeql analysis (security and quality)
  .github/workflows/codeql.yml
Labels: infrastructure

#140 Bug/improve docker stability
  server/Dockerfile
  server/build.docker.cmd
  server/docker/.env.example
  server/docker/supabase/volumes/logs/vector.yml
Labels: bug, infrastructure

#139 Feature/replace profile bio with emojicode
  client/supabase/migrations/20250419202500_rename_profiles_bio_column_to_emojicode.sql
Labels: infrastructure
