Repository PM4-FS25-DropIn/dropin, pull requests merged in 2025-05, with the labels that each got.

#145 View settingsview
  client/ios/dropin/CoreViews/SettingsViewModel.swift
Labels: enhancement

#149 update supabase components
  server/docker/supabase/docker-compose.yml
Labels: infrastructure

#143 View profileeditview
  client/ios/dropin/CoreViews/ProfileEditView.swift
Labels: enhancement

#148 Feature/avatar upload
  .github/workflows/ci-database.yml
  .github/workflows/ci-server-test.yml
  client/supabase/migrations/20250421203700_limit_avatar_file_type_size_amount.sql
  client/supabase/migrations/20250426203800_change_emojicode_constraint.sql
  client/supabase/migrations/20250429224800_apply_new_fields_on_new_user.sql
  server/package-lock.json
  server/package.json
  server/report.junit
  server/test/database/avatar.test.ts
  server/test/database/dbhelpers.ts
  server/test/server/helper.ts
  server/test/server/plugins/support.test.ts
  server/test/server/routes/example.test.ts
  server/test/server/routes/root.test.ts
Labels: infrastructure, testing

#150 Postgis function
  client/supabase/schemas/fetch_events_nearby.sql
Labels: enhancement

#152 change ci database flow name
  .github/workflows/ci-database.yml
Labels: bug, infrastructure

#154 45 [VIEW] MapView
  client/ios/dropin/Components/EventMapAnnotation.swift
  client/ios/dropin/CoreViews/EventMap.swift
  client/ios/dropin/CoreViews/MapView.swift
Labels: enhancement

#153 Update ci-database.yml
  .github/workflows/ci-database.yml
  server/package.json
  server/report.junit
Labels: bug

#189 Improved Navigationstack flow and removed nested ones
  client/ios/DropIn/Chats/ChatListView.swift
  client/ios/DropIn/Components/Forms/DropInEventForm.swift
  client/ios/DropIn/Components/TabBar.swift
  client/ios/DropIn/CoreViews/DropInsView.swift
  client/ios/DropIn/CoreViews/EventMap.swift
  client/ios/DropIn/CoreViews/HomeView.swift
Labels: bug

#190 177 [FRONTEND] DropIn event creation wizard
  client/ios/DropIn/Chats/ChatListView.swift
  client/ios/DropIn/Components/FormFields/PhotoSelector.swift
  client/ios/DropIn/Components/Forms/DropInEventForm.swift
  client/ios/DropIn/Components/TabBar.swift
  client/ios/DropIn/CoreViews/CreateEventWizard.swift
  client/ios/DropIn/CoreViews/DropInsView.swift
  client/ios/DropIn/CoreViews/EventCreateView.swift
  client/ios/DropIn/CoreViews/EventEditView.swift
  client/ios/DropIn/CoreViews/EventMap.swift
  client/ios/DropIn/CoreViews/HomeView.swift
  client/ios/DropIn/Enums.swift
  client/ios/DropIn/TextFieldStyles.swift
  client/ios/DropIn/ViewModels/CreateEventWizardViewModel.swift
Labels: enhancement

#185 Improved image display
  client/ios/DropIn/Components/Events/EventCard.swift
  client/ios/DropIn/Components/Events/EventRowItem.swift
  client/ios/DropIn/Components/Lists/AllEventsList.swift
  client/ios/DropIn/Components/MapEventItemDetailSheet.swift
  client/ios/DropIn/CoreViews/EventDetailView.swift
  client/ios/DropIn/DummyEvent.swift
  client/ios/DropIn/Stores/EventStore.swift
Labels: enhancement

#195 Major Bug fixes and improvements
  client/ios/DropIn/Authentication/SignInView.swift
  client/ios/DropIn/Authentication/SignUpView.swift
  client/ios/DropIn/Components/DropInButton.swift
  client/ios/DropIn/Components/DropOutButton.swift
  client/ios/DropIn/Components/Events/EventCard.swift
  client/ios/DropIn/Components/Events/EventCountdown.swift
  client/ios/DropIn/Components/Events/EventMarker.swift
  client/ios/DropIn/Components/Events/EventQuickInfo.swift
  client/ios/DropIn/Components/Events/EventRowItem.swift
  client/ios/DropIn/Components/Events/StatusBadges.swift
  client/ios/DropIn/Components/FormFields/AuthSecureField.swift
  client/ios/DropIn/Components/FormFields/AuthTextField.swift
  client/ios/DropIn/Components/Forms/DropInEventForm.swift
  client/ios/DropIn/Components/Lists/AllEventsList.swift
  client/ios/DropIn/Components/Lists/DiscoveryEventList.swift
  client/ios/DropIn/Components/Lists/MyEventsList.swift
  client/ios/DropIn/Components/MapEventItemDetailSheet.swift
  client/ios/DropIn/CoreViews/CreateEventWizard.swift
  client/ios/DropIn/CoreViews/DropInListView.swift
  client/ios/DropIn/CoreViews/DropInsView.swift
  client/ios/DropIn/CoreViews/EventDetailView.swift
  client/ios/DropIn/CoreViews/EventEditView.swift
  client/ios/DropIn/CoreViews/EventMap.swift
  client/ios/DropIn/CoreViews/ProfileEditView.swift
  client/ios/DropIn/Modifiers/ButtonStyles.swift
  client/ios/DropIn/Onboarding/OnboardingStartView.swift
  client/ios/DropIn/Onboarding/OnboardingView.swift
  client/ios/DropIn/Stores/EventStore.swift
Labels: bug, enhancement

#200 Feature/event table tests
  client/supabase/migrations/20250511150100_add_messages_primary_key.sql
  server/test/database/avatar.test.ts
  server/test/database/dbhelpers.ts
  server/test/database/event.test.ts
  server/test/database/event_joins.test.ts
Labels: testing

#199 198 [WORKFLOW] Fixing TestFlight build workflow + Logos
  client/ios/DropIn.xcodeproj/project.pbxproj
  client/ios/DropIn/Assets.xcassets/AppIcon.appiconset/Contents.json
  client/ios/DropIn/Assets.xcassets/AppIcon.appiconset/DropInDark.png
  client/ios/DropIn/Assets.xcassets/AppIcon.appiconset/DropInGrayScale.png
  client/ios/DropIn/Assets.xcassets/AppIcon.appiconset/DropInLight.png
  client/ios/DropIn/Components/Events/EventCard.swift
  client/ios/DropIn/Components/Events/EventCountdown.swift
  client/ios/DropIn/CoreViews/ProfileView.swift
  client/ios/DropIn/Info.plist
Labels: enhancement

#204 114 [BACKEND] Spatial data fetching with PostGIS
  client/ios/DropIn.xcodeproj/xcshareddata/xcschemes/DropIn.xcscheme
  client/ios/DropIn/Assets.xcassets/AppIcon.appiconset/Contents.json
  client/ios/DropIn/Assets.xcassets/AppIcon.appiconset/DropInDark.png
  client/ios/DropIn/Assets.xcassets/AppIcon.appiconset/DropInTransparent.png
  client/ios/DropIn/Assets.xcassets/Onboarding/location-permission.imageset/Contents.json
  client/ios/DropIn/Assets.xcassets/Onboarding/location-permission.imageset/location-permission.svg
  client/ios/DropIn/Chats/ChatRoomView.swift
  client/ios/DropIn/Components/Events/EventCard.swift
  client/ios/DropIn/Components/Events/EventCategoryTabView.swift
  client/ios/DropIn/Components/Events/EventRowItem.swift
  client/ios/DropIn/Components/Lists/AllEventsList.swift
  client/ios/DropIn/Components/Lists/DiscoveryEventList.swift
  client/ios/DropIn/CoreViews/CreateEventWizard.swift
  client/ios/DropIn/CoreViews/EventDetailView.swift
  client/ios/DropIn/CoreViews/EventEditView.swift
  client/ios/DropIn/CoreViews/EventMap.swift
  client/ios/DropIn/Models/Models.swift
  client/ios/DropIn/Models/SampleEvent.swift
  client/ios/DropIn/Onboarding/OnboardingData.swift
  client/ios/DropIn/Services/LocationService.swift
  client/ios/DropIn/Stores/EventStore.swift
  client/ios/DropIn/Supabase.swift
  client/ios/DropIn/ViewModels/CreateEventWizardViewModel.swift
  client/ios/DropIn/ViewModels/DiscoveryEventListViewModel.swift
  client/ios/DropIn/ViewModels/EventMapViewModel.swift
  client/supabase/migrations/20250411161852_create_events_table.sql
  client/supabase/migrations/20250411183955_create_view_events_not_joined.sql
  client/supabase/migrations/20250412155222_create_view_all_joined_events_of_user.sql
  client/supabase/migrations/20250412234505_create_event_feed_fetch_function.sql
  client/supabase/migrations/20250522105225_create_get_events_in_region_function.sql
  client/supabase/migrations/20250522130457_create_insert_event_function.sql
  client/supabase/migrations/20250522135843_create_update_event_function.sql
  client/supabase/migrations/20250522170711_create_get_events_fallback_function.sql
  client/supabase/seed.sql
Labels: bug, enhancement

#208 Remove deprecated features
  client/ios/DropIn/CoreViews/ProfileView.swift
  client/ios/DropIn/CoreViews/SettingsView.swift
  client/ios/DropIn/ViewModels/SettingsViewModel.swift
Labels: enhancement
